name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write # Permisos para desplegar en GitHub Pages
  id-token: write # Necesario para autenticación OIDC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Upload Storybook artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./storybook-static

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write # Permisos para escribir en Pages
      id-token: write # Para autenticación

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
